blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/CloudPasture/kubevirt-shepherd/discussions
    about: Please use GitHub Discussions for questions and general discussions
  - name: Security Vulnerabilities
    url: https://github.com/CloudPasture/kubevirt-shepherd/security/policy
    about: Please report security vulnerabilities following our security policy
